# Create an image containing the dependencies required for the CI pipeline

FROM holgermogensen/voil-ci:adae

# Update apt-get index
RUN apt-get update

# Install utilities
RUN apt-get install -y git
