name: Build and Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        name: Build and Test
        runs-on: ubuntu-latest
        container:
            image: holgermogensen/voil-ci:adae-node
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - name: Setup Rust Toolchain
              run: |
                  cargo update
                  rustup default stable
            - name: Setup Credentials for Accessing Private Adae Repo
              run: git config --global url."https://${{ secrets.GIT_CREDENTIALS }}@github.com".insteadOf https://github.com
            - name: Install Dependencies
              run: bun install
            - name: Check Formatting
              run: cargo fmt --all -- --check
            - name: Check with Clippy
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Build
              run: bun run build-debug
            - name: Run Tests
              run: bun test
