name: Build and Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build_and_test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: npm i
            - name: Build
              run: npm run build-debug
            - name: Run Tests
              run: npm test
