name: Build and Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        name: Build and Test
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - name: Setup Credentials
              run: git config --global url."https://${{ secrets.GIT_CREDENTIALS }}@github.com".insteadOf https://github.com
            - name: Update apt index
              run: sudo apt update
            - name: Install ALSA
              run: sudo apt install -y libasound2-dev
            - name: Install Dependencies
              run: npm ci
            - name: Check with Clippy
              run: |
                  cargo update
                  cargo clippy --all-targets --all-features -- -D warnings
            - name: Build
              run: npm run build-debug
            - name: Run Tests
              run: npm test
